name: PHP Tests

on:
  push:
    
  pull_request:


permissions:
  contents: read

jobs:
  test74:
    runs-on: php:7.4
    steps:
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Run test suite
      run: composer run-script test
  test80:
    runs-on: php:8.0
    steps:
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Run test suite
      run: composer run-script test
  test81:
    runs-on: php:8.1
    steps:
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Run test suite
      run: composer run-script test
  test82:
    runs-on: php:8.2
    steps:
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Run test suite
      run: composer run-script test
      
