name: PHP Tests

on:
  push:

  pull_request:


permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [  8.0, 8.1, 8.2,8.3,8.4,8.5 ]
    steps:
      - uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        run: composer upgrade --prefer-dist --no-progress
      - name: Run test suite
        run: composer run-script test

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.0, 8.1, 8.2,8.3,8.4,8.5 ]
    steps:
      - uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        run: composer upgrade --prefer-dist --no-progress
      - name: Run test suite
        run: composer run-script phpstan
