name: PHP Tests

on:
  push:

  pull_request:


permissions:
  contents: read

jobs:
  test74:
    runs-on: ubuntu-latest
    steps:
      - uses: php-actions/phpunit@v3
        with:
          php-version: '7.4'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run test suite
        run: composer run-script test
  test80:
    runs-on: ubuntu-latest
    steps:
      - uses: php-actions/phpunit@v3
        with:
          php-version: '8.0'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run test suite
        run: composer run-script test
  test81:
    runs-on: ubuntu-latest
    steps:
      - uses: php-actions/phpunit@v3
        with:
          php-version: '8.1'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run test suite
        run: composer run-script test
  test82:
    runs-on: ubuntu-latest
    steps:
      - uses: php-actions/phpunit@v3
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run test suite
        run: composer run-script test
      
